#!/bin/bash

# Make sure LXDE runs us in a terminal
if ! test "a$1" == at; then lxterminal -e '/bin/bash -c "$HOME/disorder-notes/spreadsheets/update-git t"'; exit; fi

echo Starting
if ! cd ~/disorder-notes/spreadsheets; then echo directory fail; read; exit 1; fi
echo Syncing...
git pull &&
for N in ~/Desktop/For\ oncofocus/*.xlsx; do
  export B="$(echo "$N"|sed -e 's,.*/,,' -e 's/.xlsx*$//')"
  echo "Converting $N to CSV"
  ssconvert -S "$N" "$B.%s.csv"
  echo "Converting $N to HTML"
  ssconvert -S "$N" "$B.%s.html"
  echo "Converting $N to REC"
  for H in "$B".*.html ; do
      echo "$H"
      ./html2rec.py "$(echo "$H"|sed -e s/.html$//)" < "$H" > ../recfiles/"$(echo "$H"|sed -e s/html$/rec/)"
  done
done &&
echo Committing... &&
git add *csv *html *rec &&
git commit -am update &&
echo Uploading... &&
git push &&
echo Done && exit
